#region           = "ap-south-1"
project_name  = "redmi"
project_env   = "Production"
instance_type = "t2.micro"
#hosted_zone_name = "abhishekkrishna.site"
#hostname         = "shopping"
owner  = "Abhi"
ami-id = "ami-02e94b011299ef128"
